[project]
name = "agents-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen>=0.8.0",
    "jupyter>=1.1.1",
    "numpy>=2.2.3",
    "openai>=1.65.4",
    "pandas>=2.2.3",
    "pre-commit>=4.1.0",
]
