weather_collection:
  description: >
    Collect the weather forecast for {location} on {date}.
# Use the get_weather tool with the city name directly as a string argument:
# get_weather("{location}")
  expected_output: >
    The weather forecast for {location} on {date} is {forecast}.
  agent: weather_assistant

activities_suggestion:
  description: >
    Collect and suggest a list of potential activities for the city {location} on {date} based
    on the weather forecast: {forecast}.
  expected_output: >
    List of activities for the city {location} on {date} based on the weather forecast {forecast}: {activities}.
  agent: activities_searcher
