weather_collection_task:
  description: >
    Collect the weather forecast for {city}, {country}, {administrative_area} between {start_date} and {end_date}.
  expected_output: >
    The weather forecast for {city}, {country}, {administrative_area} between {start_date} and {end_date} is {forecast}.
  agent: weather_assistant

activities_planning_task:
  description: >
    Research and find cool things to do at {city}.
    Focus on activities and events that match the weather forecast.
    Utilize internet search tools and recommendation engines to gather the information.

    Traveler's information:

    - location: {city}

    - date: {date}

#  - weather forecast: {forecast}

  expected_output: >
    A list of recommended activities and events for the location and date.
    Each entry should include the activity name, location, booking information, a brief description
    and why it is appropriate for the weather forecast.
    And potential reviews and ratings of the activities.
  agent: activities_planner
